# Generated by Django 2.2.4 on 2019-09-02 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('robotinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ytrbts',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
    ]
